Repository AY2425S2-CS2113-W12-1/tp, pull requests merged in 2025-03, with the labels that each got.

#48 Minor path bug fix
  src/main/java/modmate/download/HttpUtil.java
  src/main/java/modmate/download/nusmods/NUSModsAPI.java
  src/main/java/modmate/download/nusmods/NUSModsUtil.java
Labels: priority.High

#50 Link mod with events
  .gitignore
  src/main/java/modmate/CommandCenter.java
  src/main/java/modmate/Main.java
  src/main/java/modmate/download/json/JSONKey.java
  src/main/java/modmate/download/json/JSONParser.java
  src/main/java/modmate/download/json/ModJSONParser.java
  src/main/java/modmate/download/json/ModJSONUtil.java
  src/main/java/modmate/download/json/mod/CondensedModJSONKey.java
  src/main/java/modmate/download/json/mod/CondensedModJSONParser.java
  src/main/java/modmate/download/json/mod/ModJSONKey.java
  src/main/java/modmate/download/json/mod/ModJSONParser.java
  src/main/java/modmate/download/json/mod/attribute/ModAttrJSONKey.java
  src/main/java/modmate/download/json/mod/attribute/ModAttrJSONParser.java
  src/main/java/modmate/download/json/timetable/TimetableJSONKey.java
  src/main/java/modmate/download/json/timetable/TimetableJSONParser.java
  src/main/java/modmate/download/json/timetable/lesson/LessonJSONKey.java
  src/main/java/modmate/download/json/timetable/lesson/LessonJSONParser.java
  src/main/java/modmate/download/json/timetable/week/WeekRangeJSONKey.java
  src/main/java/modmate/download/json/timetable/week/WeekRangeJSONParser.java
  src/main/java/modmate/download/nusmods/NUSModsAPI.java
  src/main/java/modmate/event/Event.java
  src/main/java/modmate/event/Lecture.java
  src/main/java/modmate/event/Tutorial.java
  src/main/java/modmate/mod/CondensedMod.java
  src/main/java/modmate/mod/Mod.java
  src/main/java/modmate/mod/attribute/ModAttributes.java
  src/main/java/modmate/timetable/Lesson.java
  src/main/java/modmate/timetable/Period.java
  src/main/java/modmate/timetable/Semester.java
  src/main/java/modmate/timetable/Timetable.java
  src/main/java/modmate/timetable/WeekRange.java
  src/main/java/modmate/user/Schedule.java
  src/main/java/modmate/user/User.java
Labels: priority.High

#57 Add getDouble method to JSONParser and update ModAttributes to use double for units
  src/main/java/modmate/download/json/JSONParser.java
  src/main/java/modmate/download/json/mod/attribute/ModAttrJSONParser.java
  src/main/java/modmate/mod/attribute/ModAttributes.java
Labels: priority.Medium

#59 Add Telegram notification workflow for commits and pull requests
  .github/workflows/telegram.yml
Labels: priority.Low

#66 Update Telegram notification workflow triggers
  .github/workflows/telegram.yml
  .github/workflows/telegram_comment.yml
  .github/workflows/telegram_gradle.yml
  .github/workflows/telegram_issue.yml
Labels: priority.Low

#67 Fix message formatting in Telegram workflow files
  .github/workflows/telegram_comment.yml
  .github/workflows/telegram_gradle.yml
  .github/workflows/telegram_issue.yml
Labels: priority.Low

#68 Add JAVA_CI_FAILURE environment variable to Telegram workflow
  .github/workflows/telegram_comment.yml
  .github/workflows/telegram_gradle.yml
  .github/workflows/telegram_issue.yml
Labels: priority.Low

#75 Fixed JUnit using non-existing constructor for WeeklyWorkload
  src/main/java/modmate/mod/Mod.java
  src/main/java/modmate/mod/attribute/ModAttributes.java
Labels: priority.Medium

#76 Remove Telegram notification workflows
  .github/workflows/telegram_comment.yml
  .github/workflows/telegram_gradle.yml
  .github/workflows/telegram_issue.yml
Labels: priority.Medium
